manifest = "2b1421bfac43eb94fa4a24fe7544ef46eb7ed5dd284c7038b0fe2a81c2415c2b"

[[dependency]]
package = "github.com/buckaroo-pm/host-core-foundation"
target = "//:core-foundation"

[[dependency]]
package = "github.com/buckaroo-pm/realm-core"
target = "//:realm-core"

[lock."github.com/buckaroo-pm/host-core-foundation"]
versions = [ "branch=master" ]
revision = "fd7081ffe1244afb86c41c2d41d3603f851feae8"

[lock."github.com/buckaroo-pm/realm-core"]
versions = [ "branch=master" ]
revision = "42e4b262e922d6026a182af2eb2f583a4de49072"

[lock."github.com/buckaroo-pm/taocpp-pegtl"]
versions = [ "2.7.1" ]
revision = "539160b1344b901187f282a52a90ce1b69d84e0f"
