manifest = "b93b4ee67fede15760ee58379f96f7e589f3de0523db4b8ba060d8c8c3b0c2e0"

[[dependency]]
package = "github.com/buckaroo-pm/host-core-foundation"
target = "//:core-foundation"

[[dependency]]
package = "github.com/buckaroo-pm/host-security"
target = "//:security"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[[dependency]]
package = "github.com/buckaroo-pm/realm-core"
target = "//:realm-core"

[[dependency]]
package = "github.com/buckaroo-pm/realm-sync-cocoa"
target = "//:realm"

[[dependency]]
package = "github.com/buckaroo-pm/realm-sync-cocoa"
target = "//:realm-parser"

[lock."github.com/buckaroo-pm/host-core-foundation"]
versions = [ "branch=master" ]
revision = "fd7081ffe1244afb86c41c2d41d3603f851feae8"

[lock."github.com/buckaroo-pm/host-security"]
versions = [ "branch=master" ]
revision = "f7aba7ed43bd385648cb550128ce69800172343c"

[lock."github.com/buckaroo-pm/madler-zlib"]
versions = [ "1.2.11" ]
revision = "cbbc5ea260a454509d0f461de248b8e0b67bc839"

[lock."github.com/buckaroo-pm/realm-core"]
versions = [ "branch=master" ]
revision = "9849b5ac551a653ec0d541a7c13129c9b9de1bd3"

[lock."github.com/buckaroo-pm/realm-sync-cocoa"]
versions = [ "3.14.12" ]
revision = "bcfadb6c672da4a064734f802601fb1f89a8dbac"

[lock."github.com/buckaroo-pm/taocpp-pegtl"]
versions = [ "2.7.1" ]
revision = "539160b1344b901187f282a52a90ce1b69d84e0f"
